title: Ferengi Rules of Acquisition
description: A complete consolidated list of all the known Ferengi Rules of Acquisition from the Star Trek universe.
tagline: Star Trek Universe
theme: jekyll-theme-midnight

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - .gitignore
  - docker-compose.yaml
  - Dockerfile
  - makefile
